# Rutas locales de arranque para dependencias WSO2 usadas por start_demo.sh

WSO2_ROOT=/Users/rafaelgd/Develop/wso2/demos
WSO2_IS_START_SCRIPT=/Users/rafaelgd/Develop/wso2/demos/IS/wso2is-7.3.0/bin/wso2server.sh
WSO2_APIM_START_SCRIPT=/Users/rafaelgd/Develop/wso2/demos/apim/bin/api-manager.sh

# Variables requeridas por deployment.toml para la integración AI Gateway Manager
GATEWAY_CONTROLPLANE_HOST=localhost:9243
GATEWAY_REGISTRATION_TOKEN=5b60b5df-5126-4b78-b0af-6e48540e5c1b-lE0-NH1FX0h0_wb3ZpdQfUWjTUpeo1R8m8v2fHT8Vbc